package com.ovea.billing

enum BillingEventType {
    BUY_REQUESTED,
    BUY_REQUEST_ACCEPTED,
    BUY_PENDING,
    BUY_COMPLETED,

    CANCEL_REQUESTED,
    CANCEL_REQUEST_ACCEPTED,
    CANCEL_PENDING,
    CANCEL_COMPLETED,

    CALLBACK_REQUEST,
    CALLBACK_REQUEST_ACCEPTED
}
