package com.ovea.billing

enum BillingEventType {
    BUY_REQUESTED,
    BUY_REQUEST_ACCEPTED,
    BUY_PENDING,
    BUY_COMPLETED,

    CANCEL_REQUESTED,
    CANCEL_REQUEST_ACCEPTED,
    CANCEL_PENDING,
    CANCEL_COMPLETED,

    CALLBACK_REQUEST,
    CALLBACK_BUY_ACCEPTED,
    CALLBACK_BUY_PENDING,
    CALLBACK_BUY_REJECTED,

    RECOVER_REQUEST,
    RECOVER_ACCEPTED,

    RENEWAL_REQUEST,
    RENEWAL_ACCEPTED,
    RENEWAL_REJECTED
}
